package kcart.view.carview;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import kcart.dao.CarDAO;
import kcart.daoimpl.CarDAOImpl;
import kcart.model.Car;
import kcart.util.Message;

public class EditCar extends javax.swing.JFrame {
    private int carId; // From CarMenu referencing the selected row/car.
    
    public EditCar (){
        
    }
    
    public EditCar(int carId) {
        initComponents();
        this.carId = carId;
        loadCarDetails();
    }
    
    private void loadCarDetails() {
        CarDAO carDao = new CarDAOImpl();
        Car car = carDao.getCarById(carId);
        
        if (car != null) {
            txtPlateNo.setText(car.getPlateNo());
            txtBrand.setText(car.getBrand());
            txtModel.setText(car.getModel());
            cmbType.setSelectedItem(car.getCarType());
            txtYear.setText(String.valueOf(car.getYear()));
            txtColor.setText(car.getColor());
            cmbTransmission.setSelectedItem(car.getTransmissionType());
            cmbFuel.setSelectedItem(car.getFuelType());
            txtSeat.setText(String.valueOf(car.getSeatCap()));
            txtDailyRate.setText(String.valueOf(car.getDailyRate()));
            cmbStatus.setSelectedItem(car.getCarStatus());

            if (car.getCarPhoto() != null) {
                ImageIcon icon = new ImageIcon(car.getCarPhoto());
                Image scaled = icon.getImage().getScaledInstance(
                    lblCarImage.getWidth(),
                    lblCarImage.getHeight(),
                    Image.SCALE_SMOOTH
                );
                lblCarImage.setIcon(new ImageIcon(scaled));
            } else {
                lblCarImage.setIcon(null);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlContent1 = new javax.swing.JPanel();
        lblBrand = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblTransmission = new javax.swing.JLabel();
        lblFuel = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();
        lblPlateNo = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        lblSeat = new javax.swing.JLabel();
        lblDailyRate = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        lblCarImage = new javax.swing.JLabel();
        btnImportPhoto = new javax.swing.JButton();
        cmbTransmission = new javax.swing.JComboBox<>();
        cmbFuel = new javax.swing.JComboBox<>();
        cmbStatus = new javax.swing.JComboBox<>();
        txtPlateNo = new javax.swing.JTextField();
        txtBrand = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        txtSeat = new javax.swing.JTextField();
        txtDailyRate = new javax.swing.JTextField();
        lblColor = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        cmbType = new javax.swing.JComboBox<>();
        lblExtra1 = new javax.swing.JLabel();
        lblExtra2 = new javax.swing.JLabel();
        pnlContent3 = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));

        pnlMain.setBackground(new java.awt.Color(0, 0, 0));
        pnlMain.setPreferredSize(new java.awt.Dimension(1000, 600));

        pnlContent1.setBackground(new java.awt.Color(0, 0, 0));

        lblBrand.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBrand.setForeground(new java.awt.Color(255, 255, 255));
        lblBrand.setText("Brand:");
        lblBrand.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblModel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblModel.setForeground(new java.awt.Color(255, 255, 255));
        lblModel.setText("Model:");
        lblModel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblTransmission.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTransmission.setForeground(new java.awt.Color(255, 255, 255));
        lblTransmission.setText("Transmission:");
        lblTransmission.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblFuel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFuel.setForeground(new java.awt.Color(255, 255, 255));
        lblFuel.setText("Fuel:");
        lblFuel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblHeader.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblHeader.setText("Edit Car");
        lblHeader.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblPlateNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPlateNo.setForeground(new java.awt.Color(255, 255, 255));
        lblPlateNo.setText("Plate No:");
        lblPlateNo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblType.setForeground(new java.awt.Color(255, 255, 255));
        lblType.setText("Type:");
        lblType.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblYear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblYear.setForeground(new java.awt.Color(255, 255, 255));
        lblYear.setText("Year:");
        lblYear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblSeat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSeat.setForeground(new java.awt.Color(255, 255, 255));
        lblSeat.setText("Seat:");
        lblSeat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblDailyRate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDailyRate.setForeground(new java.awt.Color(255, 255, 255));
        lblDailyRate.setText("Daily Rate:");
        lblDailyRate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblStatus.setText("Status:");
        lblStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblPhoto.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblPhoto.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoto.setText("Photo:");
        lblPhoto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblCarImage.setBackground(new java.awt.Color(255, 255, 255));
        lblCarImage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCarImage.setForeground(new java.awt.Color(255, 255, 255));

        btnImportPhoto.setBackground(new java.awt.Color(255, 255, 255));
        btnImportPhoto.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnImportPhoto.setForeground(new java.awt.Color(0, 0, 0));
        btnImportPhoto.setText("Import");
        btnImportPhoto.setFocusable(false);
        btnImportPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportPhotoActionPerformed(evt);
            }
        });

        cmbTransmission.setBackground(new java.awt.Color(255, 255, 255));
        cmbTransmission.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbTransmission.setForeground(new java.awt.Color(0, 0, 0));
        cmbTransmission.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automatic", "Manual" }));

        cmbFuel.setBackground(new java.awt.Color(255, 255, 255));
        cmbFuel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbFuel.setForeground(new java.awt.Color(0, 0, 0));
        cmbFuel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gasoline", "Diesel", "Electric", "Hybrid" }));

        cmbStatus.setBackground(new java.awt.Color(255, 255, 255));
        cmbStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbStatus.setForeground(new java.awt.Color(0, 0, 0));
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Reserved", "Rented", "Maintenance" }));

        txtPlateNo.setBackground(new java.awt.Color(255, 255, 255));
        txtPlateNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPlateNo.setForeground(new java.awt.Color(0, 0, 0));

        txtBrand.setBackground(new java.awt.Color(255, 255, 255));
        txtBrand.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBrand.setForeground(new java.awt.Color(0, 0, 0));

        txtModel.setBackground(new java.awt.Color(255, 255, 255));
        txtModel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtModel.setForeground(new java.awt.Color(0, 0, 0));

        txtYear.setBackground(new java.awt.Color(255, 255, 255));
        txtYear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtYear.setForeground(new java.awt.Color(0, 0, 0));

        txtSeat.setBackground(new java.awt.Color(255, 255, 255));
        txtSeat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSeat.setForeground(new java.awt.Color(0, 0, 0));

        txtDailyRate.setBackground(new java.awt.Color(255, 255, 255));
        txtDailyRate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDailyRate.setForeground(new java.awt.Color(0, 0, 0));

        lblColor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblColor.setForeground(new java.awt.Color(255, 255, 255));
        lblColor.setText("Color:");
        lblColor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtColor.setBackground(new java.awt.Color(255, 255, 255));
        txtColor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtColor.setForeground(new java.awt.Color(0, 0, 0));

        cmbType.setBackground(new java.awt.Color(255, 255, 255));
        cmbType.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbType.setForeground(new java.awt.Color(0, 0, 0));
        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedan", "SUV", "Hatchback", "MPV", "Van", "Pickup" }));

        lblExtra1.setBackground(new java.awt.Color(255, 255, 255));
        lblExtra1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblExtra1.setForeground(new java.awt.Color(255, 255, 255));

        lblExtra2.setBackground(new java.awt.Color(255, 255, 255));
        lblExtra2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblExtra2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlContent1Layout = new javax.swing.GroupLayout(pnlContent1);
        pnlContent1.setLayout(pnlContent1Layout);
        pnlContent1Layout.setHorizontalGroup(
            pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContent1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContent1Layout.createSequentialGroup()
                        .addComponent(lblHeader)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlContent1Layout.createSequentialGroup()
                        .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlContent1Layout.createSequentialGroup()
                                .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPlateNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblBrand)
                                    .addComponent(lblType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlContent1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlContent1Layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(txtPlateNo)
                                                .addGap(21, 21, 21))
                                            .addGroup(pnlContent1Layout.createSequentialGroup()
                                                .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtBrand)
                                                    .addComponent(txtModel)
                                                    .addComponent(txtYear)
                                                    .addComponent(cmbType, 0, 351, Short.MAX_VALUE))
                                                .addGap(22, 22, 22))))
                                    .addGroup(pnlContent1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtColor)
                                        .addGap(22, 22, 22))))
                            .addGroup(pnlContent1Layout.createSequentialGroup()
                                .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnImportPhoto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCarImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(22, 22, 22)))
                        .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlContent1Layout.createSequentialGroup()
                                .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTransmission)
                                    .addComponent(lblFuel)
                                    .addComponent(lblSeat)
                                    .addComponent(lblDailyRate)
                                    .addComponent(lblStatus))
                                .addGap(18, 18, 18)
                                .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbTransmission, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbFuel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbStatus, 0, 362, Short.MAX_VALUE)
                                    .addComponent(txtSeat)
                                    .addComponent(txtDailyRate, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(lblExtra1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblExtra2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(30, 30, 30))
        );
        pnlContent1Layout.setVerticalGroup(
            pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContent1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContent1Layout.createSequentialGroup()
                        .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPlateNo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPlateNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(lblBrand))
                    .addGroup(pnlContent1Layout.createSequentialGroup()
                        .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTransmission)
                            .addComponent(cmbTransmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFuel)
                            .addComponent(cmbFuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSeat)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblModel)
                            .addComponent(txtSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDailyRate)
                            .addComponent(lblType)
                            .addComponent(txtDailyRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStatus)
                            .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblYear))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblExtra1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblColor)
                        .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContent1Layout.createSequentialGroup()
                        .addComponent(lblPhoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnImportPhoto))
                    .addComponent(lblCarImage, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExtra2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlContent3.setBackground(new java.awt.Color(0, 0, 0));

        btnEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(0, 0, 0));
        btnEdit.setText("Edit");
        btnEdit.setBorder(null);
        btnEdit.setFocusable(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(255, 255, 255));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(0, 0, 0));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(null);
        btnCancel.setFocusable(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlContent3Layout = new javax.swing.GroupLayout(pnlContent3);
        pnlContent3.setLayout(pnlContent3Layout);
        pnlContent3Layout.setHorizontalGroup(
            pnlContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContent3Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContent3Layout.setVerticalGroup(
            pnlContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContent3Layout.createSequentialGroup()
                .addGroup(pnlContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlContent3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlContent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContent3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImportPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportPhotoActionPerformed
        try {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Select Car Photo");
            fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

            // Filter only image files
            fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
                "Image files", "jpg", "jpeg", "png", "gif"
            ));

            int result = fileChooser.showOpenDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                java.io.File file = fileChooser.getSelectedFile();

                // Load image.
                ImageIcon originalIcon = new ImageIcon(file.getAbsolutePath());
                java.awt.Image img = originalIcon.getImage();

                // Scale image to fit lblCarPhoto size.
                java.awt.Image scaledImg = img.getScaledInstance(
                    lblCarImage.getWidth(),
                    lblCarImage.getHeight(),
                    java.awt.Image.SCALE_SMOOTH
                );

                // Set scaled image as icon.
                lblCarImage.setIcon(new ImageIcon(scaledImg));

                Message.show("Photo imported successfully!", "Import");
            }
        } catch (Exception e) {
            Message.error("Error importing photo:\n" + e.getMessage());
        }
    }//GEN-LAST:event_btnImportPhotoActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
            // Validation: ensure required fields are not empty.
            if (txtPlateNo.getText().trim().isEmpty() ||
                txtBrand.getText().trim().isEmpty() ||
                txtModel.getText().trim().isEmpty() ||
                txtYear.getText().trim().isEmpty() ||
                txtColor.getText().trim().isEmpty() ||
                txtSeat.getText().trim().isEmpty() ||
                txtDailyRate.getText().trim().isEmpty()) {

                Message.error("Please fill in all required fields before editing.");
                return;
            }

            // Collect values.
            String plateNo = txtPlateNo.getText().trim();
            String brand = txtBrand.getText().trim();
            String model = txtModel.getText().trim();
            String carType = cmbType.getSelectedItem().toString();
            int year = Integer.parseInt(txtYear.getText().trim());
            String color = txtColor.getText().trim();
            String transmission = cmbTransmission.getSelectedItem().toString();
            String fuel = cmbFuel.getSelectedItem().toString();
            int seatCap = Integer.parseInt(txtSeat.getText().trim());
            double dailyRate = Double.parseDouble(txtDailyRate.getText().trim());
            String status = cmbStatus.getSelectedItem().toString();

            // Convert photo from lblCarPhoto to byte[].
            byte[] photoBytes = null;
            Icon icon = lblCarImage.getIcon();
            if (icon instanceof ImageIcon) {
                ImageIcon imgIcon = (ImageIcon) icon;
                java.awt.Image img = imgIcon.getImage();
                java.awt.image.BufferedImage bImg = new java.awt.image.BufferedImage(
                        img.getWidth(null), img.getHeight(null), java.awt.image.BufferedImage.TYPE_INT_RGB);
                java.awt.Graphics2D g2 = bImg.createGraphics();
                g2.drawImage(img, 0, 0, null);
                g2.dispose();

                java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
                javax.imageio.ImageIO.write(bImg, "jpg", baos);
                photoBytes = baos.toByteArray();
            }

            // Build Car object with carId.
            Car car = new Car(
                carId, plateNo, brand, model, carType,
                year, color, transmission, fuel,
                seatCap, dailyRate, status
            );
            car.setCarPhoto(photoBytes);

            CarDAO carDao = new CarDAOImpl();
            boolean success = carDao.editCar(car);

            if (success) {
                Message.show("Car updated successfully!", "Success");
                this.dispose(); // close Edit Car UI.
            } else {
                Message.error("Failed to update car.");
            }
        } catch (Exception e) {
            // Message.error("Error editing car:\n" + e.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnImportPhoto;
    private javax.swing.JComboBox<String> cmbFuel;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JComboBox<String> cmbTransmission;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblCarImage;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblDailyRate;
    private javax.swing.JLabel lblExtra1;
    private javax.swing.JLabel lblExtra2;
    private javax.swing.JLabel lblFuel;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblPlateNo;
    private javax.swing.JLabel lblSeat;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTransmission;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblYear;
    private javax.swing.JPanel pnlContent1;
    private javax.swing.JPanel pnlContent3;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtDailyRate;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtPlateNo;
    private javax.swing.JTextField txtSeat;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}