package kcart.view.rentalview;

import java.sql.*;
import kcart.dao.BillingDAO;
import kcart.dao.RentalDAO;
import kcart.model.Return;
import kcart.dao.ReturnDAO;
import kcart.daoimpl.BillingDAOImpl;
import kcart.daoimpl.RentalDAOImpl;
import kcart.daoimpl.ReturnDAOImpl;
import kcart.model.Billing;
import kcart.dao.CarDAO;
import kcart.daoimpl.CarDAOImpl;
import kcart.util.ActiveSession;
import kcart.util.Message;

public class AdditionalBilling extends javax.swing.JFrame {

    private int rentalId;
    private String carType, carBrand, carModel;
    private String customerName;
    private Date returnDate;
    private String condition, remark;

    public AdditionalBilling() {

    }

    public AdditionalBilling(int rentalId, String carType, String carBrand, String carModel, String customerName, Date returnDate, String condition, String remark) {
        initComponents();

        this.rentalId = rentalId;
        this.carType = carType;
        this.carBrand = carBrand;
        this.carModel = carModel;
        this.customerName = customerName;
        this.returnDate = returnDate;
        this.condition = condition;
        this.remark = remark;

        this.setLocationRelativeTo(null);
        loadRentalDetails();
    }

    private void loadRentalDetails() {
        txtRentalId.setText(String.valueOf(rentalId));
        txtCustomerName.setText(customerName);
        cmbCarType.setSelectedItem(carType);
        txtCarBrand.setText(carBrand);
        txtCarModel.setText(carModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlContent1 = new javax.swing.JPanel();
        lblCarType = new javax.swing.JLabel();
        lblCarBrand = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        lblCarModel = new javax.swing.JLabel();
        lblReturnDetails = new javax.swing.JLabel();
        txtRentalId = new javax.swing.JTextField();
        txtCarBrand = new javax.swing.JTextField();
        txtCarModel = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        cmbCarType = new javax.swing.JComboBox<>();
        lblRentalID = new javax.swing.JLabel();
        pnlContent2 = new javax.swing.JPanel();
        lblInvoiceDetails = new javax.swing.JLabel();
        lblPayAmount = new javax.swing.JLabel();
        lblInvoiceAmount = new javax.swing.JLabel();
        cmbMethod = new javax.swing.JComboBox<>();
        txtPayAmount = new javax.swing.JTextField();
        txtInvoiceAmount = new javax.swing.JTextField();
        lblMethod = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        lblPaymentDetails = new javax.swing.JLabel();
        pnlContent3 = new javax.swing.JPanel();
        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("KCaRT | Additional Billing");
        setMinimumSize(new java.awt.Dimension(1000, 600));

        pnlMain.setBackground(new java.awt.Color(0, 0, 0));

        pnlContent1.setBackground(new java.awt.Color(0, 0, 0));

        lblCarType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCarType.setForeground(new java.awt.Color(255, 255, 255));
        lblCarType.setText("Car Type:");
        lblCarType.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblCarBrand.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCarBrand.setForeground(new java.awt.Color(255, 255, 255));
        lblCarBrand.setText("Car Brand:");
        lblCarBrand.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblHeader.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblHeader.setText("Additional Billing");
        lblHeader.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblCustomerName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblCustomerName.setForeground(new java.awt.Color(255, 255, 255));
        lblCustomerName.setText("Customer Name:");
        lblCustomerName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblCarModel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCarModel.setForeground(new java.awt.Color(255, 255, 255));
        lblCarModel.setText("Car Model:");
        lblCarModel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblReturnDetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblReturnDetails.setForeground(new java.awt.Color(255, 255, 255));
        lblReturnDetails.setText("Return Details:");
        lblReturnDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtRentalId.setEditable(false);
        txtRentalId.setBackground(new java.awt.Color(204, 204, 204));
        txtRentalId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRentalId.setForeground(new java.awt.Color(0, 0, 0));

        txtCarBrand.setEditable(false);
        txtCarBrand.setBackground(new java.awt.Color(204, 204, 204));
        txtCarBrand.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCarBrand.setForeground(new java.awt.Color(0, 0, 0));

        txtCarModel.setEditable(false);
        txtCarModel.setBackground(new java.awt.Color(204, 204, 204));
        txtCarModel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCarModel.setForeground(new java.awt.Color(0, 0, 0));

        txtCustomerName.setEditable(false);
        txtCustomerName.setBackground(new java.awt.Color(204, 204, 204));
        txtCustomerName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCustomerName.setForeground(new java.awt.Color(0, 0, 0));

        cmbCarType.setBackground(new java.awt.Color(204, 204, 204));
        cmbCarType.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbCarType.setForeground(new java.awt.Color(0, 0, 0));
        cmbCarType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedan", "SUV", "Hatchback", "MPV", "Van", "Pickup" }));

        lblRentalID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRentalID.setForeground(new java.awt.Color(255, 255, 255));
        lblRentalID.setText("Rental ID:");
        lblRentalID.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout pnlContent1Layout = new javax.swing.GroupLayout(pnlContent1);
        pnlContent1.setLayout(pnlContent1Layout);
        pnlContent1Layout.setHorizontalGroup(
            pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContent1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContent1Layout.createSequentialGroup()
                        .addComponent(lblHeader)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContent1Layout.createSequentialGroup()
                        .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblReturnDetails)
                            .addGroup(pnlContent1Layout.createSequentialGroup()
                                .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCarType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblRentalID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(22, 22, 22)
                                .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlContent1Layout.createSequentialGroup()
                                        .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmbCarType, 0, 324, Short.MAX_VALUE)
                                            .addComponent(txtRentalId))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCarBrand)
                                            .addComponent(lblCarModel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(29, 29, 29)
                                        .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCarBrand)
                                            .addComponent(txtCarModel)))
                                    .addComponent(txtCustomerName))))
                        .addGap(39, 39, 39))))
        );
        pnlContent1Layout.setVerticalGroup(
            pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContent1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lblReturnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlContent1Layout.createSequentialGroup()
                        .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRentalId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRentalID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addComponent(lblCarType)
                        .addGap(3, 3, 3))
                    .addGroup(pnlContent1Layout.createSequentialGroup()
                        .addComponent(txtCarBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtCarModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbCarType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarModel)
                    .addGroup(pnlContent1Layout.createSequentialGroup()
                        .addComponent(lblCarBrand)
                        .addGap(26, 26, 26)))
                .addGap(5, 5, 5)
                .addGroup(pnlContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerName)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlContent2.setBackground(new java.awt.Color(0, 0, 0));

        lblInvoiceDetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblInvoiceDetails.setForeground(new java.awt.Color(255, 255, 255));
        lblInvoiceDetails.setText("Invoice Details:");
        lblInvoiceDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblPayAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPayAmount.setForeground(new java.awt.Color(255, 255, 255));
        lblPayAmount.setText("Pay Amount:");
        lblPayAmount.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblInvoiceAmount.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblInvoiceAmount.setForeground(new java.awt.Color(255, 255, 255));
        lblInvoiceAmount.setText("Invoice Amount:");
        lblInvoiceAmount.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        cmbMethod.setBackground(new java.awt.Color(255, 255, 255));
        cmbMethod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbMethod.setForeground(new java.awt.Color(0, 0, 0));
        cmbMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash" }));

        txtPayAmount.setBackground(new java.awt.Color(255, 255, 255));
        txtPayAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPayAmount.setForeground(new java.awt.Color(0, 0, 0));

        txtInvoiceAmount.setBackground(new java.awt.Color(255, 255, 255));
        txtInvoiceAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtInvoiceAmount.setForeground(new java.awt.Color(0, 0, 0));

        lblMethod.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMethod.setForeground(new java.awt.Color(255, 255, 255));
        lblMethod.setText("Method:");
        lblMethod.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblDescription.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDescription.setForeground(new java.awt.Color(255, 255, 255));
        lblDescription.setText("Description:");
        lblDescription.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtDescription.setBackground(new java.awt.Color(255, 255, 255));
        txtDescription.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDescription.setForeground(new java.awt.Color(0, 0, 0));

        lblPaymentDetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPaymentDetails.setForeground(new java.awt.Color(255, 255, 255));
        lblPaymentDetails.setText("Payment Details:");
        lblPaymentDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout pnlContent2Layout = new javax.swing.GroupLayout(pnlContent2);
        pnlContent2.setLayout(pnlContent2Layout);
        pnlContent2Layout.setHorizontalGroup(
            pnlContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContent2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInvoiceDetails)
                    .addGroup(pnlContent2Layout.createSequentialGroup()
                        .addGroup(pnlContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescription)
                            .addComponent(lblInvoiceAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInvoiceAmount)
                            .addComponent(txtDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(pnlContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPaymentDetails)
                    .addGroup(pnlContent2Layout.createSequentialGroup()
                        .addGroup(pnlContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblMethod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPayAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPayAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                            .addComponent(cmbMethod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(45, 45, 45))
        );
        pnlContent2Layout.setVerticalGroup(
            pnlContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContent2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlContent2Layout.createSequentialGroup()
                        .addComponent(lblPaymentDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPayAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPayAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlContent2Layout.createSequentialGroup()
                        .addComponent(lblInvoiceDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInvoiceAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInvoiceAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pnlContent3.setBackground(new java.awt.Color(0, 0, 0));

        btnConfirm.setBackground(new java.awt.Color(255, 255, 255));
        btnConfirm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(0, 0, 0));
        btnConfirm.setText("Confirm Transaction");
        btnConfirm.setBorder(null);
        btnConfirm.setFocusable(false);
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(255, 255, 255));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(0, 0, 0));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(null);
        btnCancel.setFocusable(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlContent3Layout = new javax.swing.GroupLayout(pnlContent3);
        pnlContent3.setLayout(pnlContent3Layout);
        pnlContent3Layout.setHorizontalGroup(
            pnlContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContent3Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContent3Layout.setVerticalGroup(
            pnlContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContent3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlContent2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlContent3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlContent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContent3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // Get invoice info.
        String invoiceDescription = txtDescription.getText().trim();
        String invoiceAmountText = txtInvoiceAmount.getText().trim();

        // Get payment info.
        String payMethod = cmbMethod.getSelectedItem().toString();
        String payAmountText = txtPayAmount.getText().trim();

        // Validate required fields.
        if (invoiceDescription.isEmpty()) {
            Message.error("Please enter the invoice description.");
            return;
        }

        if (invoiceAmountText.isEmpty()) {
            Message.error("Please enter the invoice amount.");
            return;
        }

        if (payAmountText.isEmpty()) {
            Message.error("Please enter the payment amount.");
            return;
        }

        try {
            // Convert amounts.
            double invoiceAmount = Double.parseDouble(invoiceAmountText);
            double payAmount = Double.parseDouble(payAmountText);

            // Payment must match the invoice amount.
            if (payAmount != invoiceAmount) {
                Message.error("Payment amount must match the invoice amount.");
                return;
            }

            // Get logged-in user.
            int processedBy = ActiveSession.loggedInUserId;

            // Build Return object.
            Return returnInfo = new Return(
                    rentalId,
                    processedBy,
                    returnDate,
                    condition,
                    remark
            );

            // Record return.
            ReturnDAO returnDao = new ReturnDAOImpl();

            int returnId = returnDao.addReturn(returnInfo);

            if (returnId == -1) {
                Message.error("Failed to record return.");
                return;
            }

            // Build Billing object.
            Billing billing = new Billing();

            billing.setRentalId(rentalId);
            billing.setReturnId(returnId);
            billing.setDescription(invoiceDescription);
            billing.setInvoiceAmount(invoiceAmount);
            billing.setInvoiceStatus("Paid");
            billing.setProcessedBy(processedBy);
            billing.setPayMethod(payMethod);
            billing.setPayAmount(payAmount);

            // Record invoice.
            BillingDAO billingDao = new BillingDAOImpl();

            int invoiceId = billingDao.addInvoice(billing);

            if (invoiceId == -1) {
                Message.error("Failed to record invoice.");
                return;
            }

            // Record payment.
            boolean paymentSuccess
                    = billingDao.addPayment(billing, invoiceId);

            if (!paymentSuccess) {
                Message.error("Failed to record payment.");
                return;
            }

            // Mark rental as Completed.
            RentalDAO rentalDao = new RentalDAOImpl();

            boolean rentalSuccess
                    = rentalDao.updateRentalStatus(rentalId, "Completed");

            if (!rentalSuccess) {
                Message.error("Failed to complete rental.");
                return;
            }

            // Get car ID from rental.
            int carId = rentalDao.getCarIdByRentalId(rentalId);

            if (carId == -1) {
                Message.error("Car ID not found for rental.");
                return;
            }

            // Mark car as Available.
            CarDAO carDao = new CarDAOImpl();

            boolean carSuccess
                    = carDao.updateCarStatus(carId, "Available");

            if (!carSuccess) {
                Message.error("Failed to update car status.");
                return;
            }

            Message.show("Additional billing completed successfully!", "Success");
            
            this.dispose();
        } catch (NumberFormatException e) {
            Message.error("Please enter a valid amount.");
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdditionalBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdditionalBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdditionalBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdditionalBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdditionalBilling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JComboBox<String> cmbCarType;
    private javax.swing.JComboBox<String> cmbMethod;
    private javax.swing.JLabel lblCarBrand;
    private javax.swing.JLabel lblCarModel;
    private javax.swing.JLabel lblCarType;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblInvoiceAmount;
    private javax.swing.JLabel lblInvoiceDetails;
    private javax.swing.JLabel lblMethod;
    private javax.swing.JLabel lblPayAmount;
    private javax.swing.JLabel lblPaymentDetails;
    private javax.swing.JLabel lblRentalID;
    private javax.swing.JLabel lblReturnDetails;
    private javax.swing.JPanel pnlContent1;
    private javax.swing.JPanel pnlContent2;
    private javax.swing.JPanel pnlContent3;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JTextField txtCarBrand;
    private javax.swing.JTextField txtCarModel;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtInvoiceAmount;
    private javax.swing.JTextField txtPayAmount;
    private javax.swing.JTextField txtRentalId;
    // End of variables declaration//GEN-END:variables
}
